import { AllIcons } from "@/assets/Icons";

export const icons = [
    { name: "iconUser", icon: AllIcons.IconUser },
    { name: "iconSearch", icon: AllIcons.IconSearch },
    { name: "iconLock", icon: AllIcons.IconLock },
    { name: "iconMenuDeep", icon: AllIcons.IconMenuDeep },
    { name: "iconMenuDots", icon: AllIcons.IconMenuDots },
    { name: "iconHeart", icon: AllIcons.IconHeart },
    { name: "iconMessage", icon: AllIcons.IconMessage },
    { name: "iconHeadphones", icon: AllIcons.IconHeadphones },
    { name: "iconLogin", icon: AllIcons.IconLogin },
    { name: "iconLogout", icon: AllIcons.IconLogout },
    { name: "iconAdd", icon: AllIcons.IconAdd },
    { name: "iconTag", icon: AllIcons.IconTag },
    { name: "iconShare", icon: AllIcons.IconShare },
    { name: "iconDotsHorizontal", icon: AllIcons.IconDotsHorizontal },
    { name: "iconPlane", icon: AllIcons.IconPlane },
    { name: "iconImage", icon: AllIcons.IconImage },
    { name: "iconText", icon: AllIcons.IconText },
    { name: "iconEmoji", icon: AllIcons.IconEmoji },
    { name: "iconMicrophone", icon: AllIcons.IconMicrophone },
    { name: "iconArrowUp", icon: AllIcons.IconArrowUp },
    { name: "iconArrowDown", icon: AllIcons.IconArrowDown },
    { name: "iconArrowLeft", icon: AllIcons.IconArrowLeft },
    { name: "iconArrowRight", icon: AllIcons.IconArrowRight },
    { name: "iconArrowUpDown", icon: AllIcons.IconArrowUpDown },
    { name: "iconTrash", icon: AllIcons.IconTrash },
    { name: "iconPencil", icon: AllIcons.IconPencil },
    { name: "iconX", icon: AllIcons.IconX },
    { name: "iconGoogle", icon: AllIcons.IconGoogle },
];