import { AllIcons } from "@/assets/Icons";

export const icons = [
    { name: "iconUser", icon: AllIcons.IconUser },
    { name: "Search", icon: AllIcons.IconSearch },
    { name: "iconLock", icon: AllIcons.IconLock },
    { name: "MenuDeep", icon: AllIcons.IconMenuDeep },
    { name: "MenuDots", icon: AllIcons.IconMenuDots },
    { name: "Heart", icon: AllIcons.IconHeart },
    { name: "Message", icon: AllIcons.IconMessage },
    { name: "iconH/P", icon: AllIcons.IconHeadphones },
    { name: "Login", icon: AllIcons.IconLogin },
    { name: "Logout", icon: AllIcons.IconLogout },
    { name: "iconAdd", icon: AllIcons.IconAdd },
    { name: "iconTag", icon: AllIcons.IconTag },
    { name: "iconShare", icon: AllIcons.IconShare },
    { name: "DotsHrz", icon: AllIcons.IconDotsHorizontal },
    { name: "iconPlane", icon: AllIcons.IconPlane },
    { name: "Image", icon: AllIcons.IconImage },
    { name: "iconText", icon: AllIcons.IconText },
    { name: "Emoji", icon: AllIcons.IconEmoji },
    { name: "Microphone", icon: AllIcons.IconMicrophone },
    { name: "Up", icon: AllIcons.IconArrowUp },
    { name: "Down", icon: AllIcons.IconArrowDown },
    { name: "Left", icon: AllIcons.IconArrowLeft },
    { name: "Right", icon: AllIcons.IconArrowRight },
    { name: "UpDown", icon: AllIcons.IconArrowUpDown },
    { name: "iconTrash", icon: AllIcons.IconTrash },
    { name: "Pencil", icon: AllIcons.IconPencil },
    { name: "iconX", icon: AllIcons.IconX },
    { name: "Google", icon: AllIcons.IconGoogle },
];